#!/usr/bin/with-contenv bash

# Fetch site or update existing
if [[ ! -d /config/plex-web/.git ]]; then
  echo '-----------------------'
  echo '| Installing plex-web |'
  echo '-----------------------'
  git clone https://github.com/banjoanton/plex-web.git /config/plex-web
elif [[ -d /config/plex-web/.git ]]; then
  echo '-----------------------'
  echo '|  Updating plex-web  |'
  echo '-----------------------'
  cd /config/plex-web || return
  git reset --hard origin/master
  git pull --rebase
fi

# Install requirements
cd /config/plex-web || exit 1
pip3 install -r requirements.txt

# Set Permissions
chown -R abc:abc \
	/config
#chmod 777 \
#  /config/www/plpp/cache
#chmod 777 \
#  /config/www/plpp/config